spring:
 datasource:
  url: jdbc:h2:mem:adoption-list
  username: meow
  password:
 jpa:
  show-sql: true # ver queries no console
  open-in-view: false
  hibernate:
   ddl-auto: create # validate | update | create | create-drop
  properties:
   hibernate:
    format_sql: true
 h2:
  console:
   enabled: true # acessar banco via browser
   path: /h2-console
   settings:
    trace: false
    web-allow-others: false 
